site_name: NbDocs
repo_url: https://github.com/ayasyrev/nbdocs
repo_name: nbdocs

# nav:

theme:
  name: material
  # name: mkdocs
  palette: 
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences